### PR TITLE
add travis pipeline

### PR DESCRIPTION
**Pull request by SydOps**
- add Travis pipeline
- import local package
- tuning `make.sh`

### CODE REVIEW

**Comment by SydOps** [comment]
Two notes:

1. the output of `fuseclient` is named to fuseclient.ini

```
cd ./fuseclient
go build -o cfs-fuse-client main.go
cp cfs-fuse-client mountpoint.ini ../output
cd -
```

2. I can't `go get -u github.com/coreos/etcd` successfully on my mac and travis's ubuntu environment, need your input.

https://travis-ci.org/BWITS/containerfs/builds/224160432

```
$ go get -u github.com/coreos/etcd
# github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw
../../coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:147: not enough arguments in call to runtime.AnnotateContext
```

**Comment by SydOps** [comment]
@zhengxiaochuan-3 

Got same issue after switch to build in centos

https://travis-ci.org/BWITS/containerfs/builds/224193639

**Comment by zhengxiaochuan-3** [comment]
@SydOps  hi , bill , thanks a lot for this pr . Now we have our  Travis CI ，it`s AMAZING !!!
About this build error , I will submit a issue to etcd.

**Comment by SydOps** [comment]
https://github.com/coreos/etcd/issues/7791

**Comment by SydOps** [comment]
@zhengxiaochuan-3  @jsonkey 

Don't forget to integrate your GitHub project with Travis-ci

https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by jsonkey** [comment]
ectd build error fixed 
 
go get -u github.com/coreos/etcd
change to 
go get -u github.com/coreos/etcd/cmd/etcd

**Pull request merged**
